Ruby/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'about', to: 'welcome#about', as: 'about'
  resources :votes
  resources :users
  root 'welcome#index'
end

Ruby/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Ruby/app/models/pincho.rb
class Pincho < ApplicationRecord
  has_many :votes
  has_many :voters, through: :votes, source: :user
  belongs_to :owner, class_name: 'User'
end

Ruby/app/models/user.rb
require 'bcrypt'
class User < ApplicationRecord
  has_many :votes
  has_many :pinchos, through: :votes

  attr_accessor :password

  validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
  validates :name, :presence => true, :length => { :in => 3..100 }
  validates :password, :confirmation => true
  validates_length_of :password, :in => 6..20, :on => create

  before_save :encrypt_password
  after_save :clear_password

  def encrypt_password
    return unless password.present?

    self.salt = BCrypt::Engine.generate_salt
    self.encrypted_password = BCrypt::Engine.hash_secret(password, salt)
  end

  def clear_password
    self.password = nil
  end
end

Ruby/app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :pincho
end

Ruby/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Ruby/app/controllers/pinchos_controller.rb
class PinchosController < ApplicationController
end

Ruby/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'Usuario dado de alta con éxito'
      flash[:color] = 'valid'
    else
      flash[:notice] = 'Los datos son inválidos'
      flash[:color] = 'invalid'
    end
    render 'new'
  end

  def index
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:username, :name, :password, :password_confirmation)
  end
end

Ruby/app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def index
    @votes = Vote.all
  end
end

Ruby/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

Ruby/app/helpers/application_helper.rb
module ApplicationHelper
end

Ruby/app/helpers/pinchos_helper.rb
module PinchosHelper
end

Ruby/app/helpers/users_helper.rb
module UsersHelper
end

Ruby/app/helpers/votes_helper.rb
module VotesHelper
end

Ruby/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Ruby/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pinchos</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Ruby/app/views/users/index.html.erb
<header class="intro-header">
  <div class="container">
    <div class="intro-message">
      <h1>Usuarios</h1>
    </div>
  </div>
</header>

<div class="container">
  <table class="table table-bordered table-striped">
    <tr>
      <th>Usuario</th>
      <th>Nombre</th>
    </tr>

    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.name %></td>
      </tr>
    <% end %>
  </table>
</div>

<div class="container" align="center">
  <%= link_to 'Inicio', root_path, class: "btn btn-secondary btn-lg" %>
</div>

Ruby/app/views/users/new.html.erb
<% @page_title = "Participantes | Alta" %>

<header class="intro-header">
  <div class="container">
    <div class="intro-message">
      <h1>Registro</h1>
    </div>
  </div>
</header>

<div class="section">
  <div class="container">
    <%= form_for(:user, 
        :url => {:controller => 'users', :action => 'create'}, 
        :html => {:class => "form-horizontal center"}) do |f| %>
      <div class="form-group">
        <%= f.label :username, "Usuario:", class: "control-label" %>
        <%= f.text_field :username, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :name, "Nombre:", class: "control-label" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password, class: "control-label" %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation, class: "control-label" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
      <%= f.submit "Registrar", class: "btn btn-default btn-primary" %>
    <% end %>
    <% if @user.errors.any? %>
      <ul class="Signup_Errors">
      <% for message_error in @user.errors.full_messages %>
        <li>* <%= message_error %></li>
      <% end %>
      </ul>
    <% end %>
  </div>
</div>

Ruby/app/views/votes/index.html.erb
<header class="intro-header">
  <div class="container">
    <div class="intro-message">
      <h1>Votaciones</h1>
    </div>
  </div>
</header>

<div class="container">
  <table class="table table-bordered table-striped">
    <tr>
      <th>Usuario</th>
      <th>Pincho</th>
      <th>Voto</th>
    </tr>
  
    <% @votes.each do |vote| %>
      <tr>
        <td><%= vote.user.name %></td>
        <td><%= vote.pincho.name %></td>
        <td><%= vote.value %></td>
        <td><%= link_to 'Mostrar', vote_path(vote) %></td>
      </tr>
    <% end %>
  </table>
</div>

<div class="container" align="center">
  <%= link_to 'Inicio', root_path, class: "btn btn-secondary btn-lg" %>
</div>

Ruby/app/views/welcome/about.html.erb
<%= stylesheet_link_tag "landing-page.css" %>

<!-- Header -->
<header class="intro-header">
  <div class="container">
    <div class="intro-message">
      <h1>Pinchos Vistahermosa</h1>
      <h3>Sistema de Votación para concursos de pinchos en pequeñas comunidades</h3>
      <p>Actualmente en desarrollo</p>
      <hr class="intro-divider">
      <h3>Fernando de Francisco</h3>
      <h3>2018</h3>
    </div>
  </div>
</header>

<!-- Footer -->
<footer>
  <div class="container">
    <ul class="list-inline">
      <li class="list-inline-item">
        <a href="/">Home</a>
      </li>
      <li class="footer-menu-divider list-inline-item">&sdot;</li>
      <li class="list-inline-item">
        <a href="#">About</a>
      </li>
      <li class="footer-menu-divider list-inline-item">&sdot;</li>
      <li class="list-inline-item">
        <a href="#contact">Contact</a>
      </li>
    </ul>
    <p class="copyright text-muted small">Copyright &copy; FdFDev 2018. All Rights Reserved</p>
  </div>
</footer>

Ruby/app/views/welcome/index.html.erb
<%= stylesheet_link_tag "landing-page.css" %>

<!-- Header -->
<header class="intro-header">
  <div class="container">
    <div class="intro-message">
      <h1>Pinchos Vistahermosa</h1>
      <h3>Sistema de Votación</h3>
      <hr class="intro-divider">
      <ul class="list-inline intro-social-buttons">
        <li class="list-inline-item">
          <a href="users/new" class="btn btn-secondary btn-lg">
            <i class="fa fa-twitter fa-fw"></i>
            <span class="network-name">Registrarse</span>
          </a>
        </li>
        <li class="list-inline-item">
          <a href="#" class="btn btn-secondary btn-lg">
            <i class="fa fa-github fa-fw"></i>
            <span class="network-name">Entrar</span>
          </a>
        </li>
        <li class="list-inline-item">
          <a href="votes" class="btn btn-secondary btn-lg">
            <i class="fa fa-linkedin fa-fw"></i>
            <span class="network-name">Ver Resultados</span>
          </a>
        </li>
      </ul>
    </div>
  </div>
</header>

<!-- Footer -->
<footer>
  <div class="container">
    <ul class="list-inline">
      <li class="list-inline-item">
        <a href="#">Home</a>
      </li>
      <li class="footer-menu-divider list-inline-item">&sdot;</li>
      <li class="list-inline-item">
        <a href="about">About</a>
      </li>
      <li class="footer-menu-divider list-inline-item">&sdot;</li>
      <li class="list-inline-item">
        <a href="#contact">Contact</a>
      </li>
    </ul>
    <p class="copyright text-muted small">Copyright &copy; FdFDev 2018. All Rights Reserved</p>
  </div>
</footer>